// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEn1abnHK8FZUj78hTUwaYHzM-KyiPYPE',
    appId: '1:234529339231:web:f84b160f92d5f63d6ca8ea',
    messagingSenderId: '234529339231',
    projectId: 'crud-firebase-ea9d2',
    authDomain: 'crud-firebase-ea9d2.firebaseapp.com',
    storageBucket: 'crud-firebase-ea9d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxW6kx7bXDSgmQmbpyq8SoqNrrfhbzHKc',
    appId: '1:234529339231:android:ab78682f02355bd86ca8ea',
    messagingSenderId: '234529339231',
    projectId: 'crud-firebase-ea9d2',
    storageBucket: 'crud-firebase-ea9d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA341FnpFDLZys-RhBExOPFq4e4HAmgGSw',
    appId: '1:234529339231:ios:28922957b31c780f6ca8ea',
    messagingSenderId: '234529339231',
    projectId: 'crud-firebase-ea9d2',
    storageBucket: 'crud-firebase-ea9d2.firebasestorage.app',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA341FnpFDLZys-RhBExOPFq4e4HAmgGSw',
    appId: '1:234529339231:ios:28922957b31c780f6ca8ea',
    messagingSenderId: '234529339231',
    projectId: 'crud-firebase-ea9d2',
    storageBucket: 'crud-firebase-ea9d2.firebasestorage.app',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEn1abnHK8FZUj78hTUwaYHzM-KyiPYPE',
    appId: '1:234529339231:web:b6cd2f27d0d91e7e6ca8ea',
    messagingSenderId: '234529339231',
    projectId: 'crud-firebase-ea9d2',
    authDomain: 'crud-firebase-ea9d2.firebaseapp.com',
    storageBucket: 'crud-firebase-ea9d2.firebasestorage.app',
  );
}
